name: Rinu kuttan's pipeline

# 1. Define the workflow_dispatch trigger to accept inputs
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select branch'
        required: true
        type: choice
        options:
          - master
          - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 2. Access inputs using the ${{ inputs.input_name }} syntax
      - name: Log the user inputs
        run: |
          echo "The selected environment is: ${{ inputs.branch }}"

      - name: Optional Testing Step
        # NOTE: You can safely omit ${{ }} inside the 'if' condition as it is evaluated automatically
        if: inputs.branch == 'develop'
        run: |
          echo "Branch is develop, failing intentionally..."
          exit 1
